{
 "title": "Asena Monitor",
 "tags": [ "asena" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Command Usage Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "asena_command_usage", "legendFormat": "Command - {{command}}" }
   ]
  },
  {
   "title": "Server Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "asena_server_count", "legendFormat": "Server Count - {{instance}}" }
   ]
  },
  {
   "title": "Continuing Survey Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "asena_continuing_survey_count", "legendFormat": "Count - {{instance}}" }
   ]
  },
  {
   "title": "Continuing Giveaway Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "asena_continuing_giveaway_count",
     "legendFormat": "Count - {{instance}}"
    }
   ]
  }
 ]
}